### ISSUE TITLE
Non-ascii characters are stripped

### ISSUE THREAD

**Issue by krenaud** [joelpt/sublimetext-print-to-html#1]
Scenario:
Print document containing non-ascii characters such as "åäöéüßç"

Expected result:
Characters show up as-is on printout.

Actual result:
Characters are stripped from output.

Two possible solutions:
a) Convert to html escape codes such as &amp;aring; &amp;auml; etc
b) Set character set in html header and do not strip the characters.

**Comment by joelpt** [comment]
I'll look into this soon. I'm actually aware this is happening, and it is happening because ST2/Python throws all sorts of Unicode conversion exceptions at me when it encounters these characters.

I haven't figured out a proper fix yet, but your solution (a) may do the trick.

**Comment by joelpt** [comment]
Fixed! All non-ascii characters are now encoded as XML character entities, e.g. å becomes &amp;#229;. Tested with your example characters and they came through correctly in my browser. Thanks for the idea that inspired the fix.
